/**
 * Le vocabulaire de l'analyseur local.
 *
 * PROVISOIRE : ces listes tiennent lieu de compréhension en attendant l'appel au
 * modèle. Elles sont séparées du code de décision pour rester lisibles et corrigeables
 * sans toucher à la logique.
 */

/** Verbes d'action qui font d'un passage une tâche. */
export const VERBES_ACTION = [
  'appeler',
  'relancer',
  'envoyer',
  'transmettre',
  'préparer',
  'relire',
  'rédiger',
  'écrire',
  'vérifier',
  'valider',
  'corriger',
  'finir',
  'terminer',
  'boucler',
  'lancer',
  'organiser',
  'planifier',
  'programmer',
  'caler',
  'réserver',
  'commander',
  'acheter',
  'payer',
  'signer',
  'chiffrer',
  'arbitrer',
  'trancher',
  'recruter',
  'contacter',
  'demander',
  'répondre',
  'voir',
  'faire',
  'prendre',
  'passer',
  'mettre',
  'monter',
  'revoir',
  'traiter',
  'déposer',
  'rappeler',
  'confirmer',
  'annuler',
  'déclarer',
  'inscrire',
  'ranger',
  'nettoyer',
  'trouver',
  'chercher',
  'lire',
  'comparer',
  'négocier',
  'présenter',
  'partager',
  'publier',
  'tester',
  'corriger',
  'déployer',
];

/** Amorces qui annoncent explicitement une tâche même sans verbe listé. */
export const AMORCES_TACHE = [
  'penser a',
  'il faut',
  'faut que',
  'ne pas oublier',
  'pas oublier de',
  'note de',
  'a faire',
];

/** Un engagement est une promesse faite à quelqu'un. */
export const AMORCES_ENGAGEMENT = [
  "je m'engage",
  'jai promis',
  "j'ai promis",
  'jai dit que je',
  "j'ai dit que je",
  'je me suis engage',
  'promis a',
  'je dois rendre',
  'je leur ai dit',
  'je lui ai dit',
];

/** Une attente, c'est quelqu'un qui doit quelque chose à l'utilisateur. */
export const AMORCES_ATTENTE = [
  "j'attends",
  'jattends',
  'en attente de',
  'doit me',
  'doivent me',
  'me revient',
  'me renvoie',
  'attendre le retour',
  'attendre la reponse',
  'toujours pas recu',
  'toujours pas eu',
];

export const AMORCES_DECISION = [
  'on a decide',
  'jai decide',
  "j'ai decide",
  'decision prise',
  'on part sur',
  'on retient',
  'on valide',
  'acte que',
  'on abandonne',
];

export const AMORCES_IDEE = [
  'idee',
  'et si on',
  'on pourrait',
  'ce serait bien de',
  'a creuser',
  'un jour',
  'peut-etre quon',
  "peut-etre qu'on",
];

/** Indices de conséquence forte : ce qui se passe si ce n'est pas fait. */
export const INDICES_FORT: { motif: RegExp; indice: string }[] = [
  { motif: /\burgent(e|es|s)?\b/, indice: 'annoncé comme urgent' },
  { motif: /\bcritique\b/, indice: 'annoncé comme critique' },
  { motif: /\bbloqu(e|ant|ante|es|ants)\b/, indice: "bloque quelqu'un d'autre" },
  { motif: /\bsinon\b/, indice: 'une conséquence est énoncée (« sinon »)' },
  { motif: /\brisqu(e|es|ons)\b/, indice: 'un risque est énoncé' },
  { motif: /\bclient(e|s)?\b/, indice: 'engage un client' },
  { motif: /\b(direction|codir|comex|comite)\b/, indice: 'engage la direction' },
  { motif: /\bcontrat\b/, indice: 'porte sur un contrat' },
  { motif: /\b(juridique|legal|conformite)\b/, indice: 'enjeu juridique' },
  { motif: /\b(penalite|amende|petition)\b/, indice: 'sanction financière possible' },
  { motif: /\b(production|incident|panne)\b/, indice: 'incident de production' },
  { motif: /\b(securite|accident)\b/, indice: 'enjeu de sécurité' },
  { motif: /\b(paie|salaire|budget|facture|devis)\b/, indice: 'enjeu financier' },
  { motif: /\b(deadline|echeance legale|delai legal)\b/, indice: 'délai contraint' },
  { motif: /\bimportant(e|es|s)?\b/, indice: 'annoncé comme important' },
];

/** Indices de conséquence faible : rien ne casse si ce n'est pas fait. */
export const INDICES_FAIBLE: { motif: RegExp; indice: string }[] = [
  { motif: /\bquand j'?aurai le temps\b/, indice: 'sans contrainte de temps annoncée' },
  { motif: /\bsi j'?ai le temps\b/, indice: 'sans contrainte de temps annoncée' },
  { motif: /\bpas urgent\b/, indice: 'annoncé comme non urgent' },
  { motif: /\ba l'?occasion\b/, indice: "à faire à l'occasion" },
  { motif: /\beventuellement\b/, indice: 'énoncé comme optionnel' },
  { motif: /\bsi possible\b/, indice: 'énoncé comme optionnel' },
  { motif: /\btranquillement\b/, indice: 'sans contrainte de temps annoncée' },
  { motif: /\bun jour\b/, indice: 'sans horizon' },
];

export const INDICES_PERSONNEL = [
  'maison',
  'famille',
  'enfant',
  'enfants',
  'medecin',
  'dentiste',
  'vacances',
  'perso',
  'ecole',
  'courses',
  'anniversaire',
  'voiture',
  'garage',
  'banque',
  'impots',
  'week-end',
];

export const INDICES_PROFESSIONNEL = [
  'reunion',
  'client',
  'budget',
  'equipe',
  'comite',
  'projet',
  'bureau',
  'contrat',
  'devis',
  'facture',
  'recrutement',
  'codir',
  'comex',
  'presentation',
  'atelier',
  'sprint',
  'roadmap',
];

/**
 * Mots qui portent une majuscule sans être un prénom (début de phrase, sigles usuels).
 * Sert à éviter de prendre « Demain » pour quelqu'un.
 */
export const NON_PRENOMS = new Set([
  'demain',
  'lundi',
  'mardi',
  'mercredi',
  'jeudi',
  'vendredi',
  'samedi',
  'dimanche',
  'janvier',
  'fevrier',
  'mars',
  'avril',
  'mai',
  'juin',
  'juillet',
  'aout',
  'septembre',
  'octobre',
  'novembre',
  'decembre',
  'la',
  'le',
  'les',
  'ce',
  'cette',
  'mon',
  'ma',
  'mes',
  'notre',
  'nos',
  'un',
  'une',
  'des',
  'il',
  'elle',
  'on',
  'je',
  'tout',
  'tous',
  'toute',
  'toutes',
  'midi',
  'moi',
  'lui',
  'eux',
  'nous',
  'vous',
  'demander',
  'faire',
  'voir',
]);
